project/project/project/inmakes_product_folder/movieproject/movieapp/urls.py
from django.urls import path
from .import views
app_name = 'movieapp'

urlpatterns = [

    path('',views.index,name = 'index'),
    path('movie/<int:movie_id>/',views.detail,name = 'detail'),
    path('add/',views.add_movie,name= 'add_movie'),
    path('update/<int:id>/',views.update,name = 'update')
]

project/project/project/inmakes_product_folder/movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

project/project/project/inmakes_product_folder/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to = 'gallery')

    def __str__(self):
        return self.name

project/project/project/inmakes_product_folder/movieproject/movieapp/forms.py
from django import forms
from .models import movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = movie
        fields = ['name','desc','year','img']

project/project/project/inmakes_product_folder/movieproject/movieapp/views.py
from django.shortcuts import redirect
from django.shortcuts import render
from .models import movie
from .forms import MovieForm
# Create your views here.

def index(request):
    Movie = movie.objects.all()
    context = {
        'movie_list': Movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    Movie = movie.objects.get(id = movie_id)
    return render(request,"detail.html",{'movie':Movie})

def add_movie(request):
    if request.method == "POST":
        name = request.POST.get ('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        Movies = movie(name=name,desc=desc,year=year,img=img)
        Movies.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    Movie = movie.objects.get(id=id)
    form = MovieForm(request.POST or None,request.FILES,instance = Movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'from':form,'movie':Movie})

project/project/project/inmakes_product_folder/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body
%}
<form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <input type="text" name="name" placeholder="Movie Name">
      <input type="text" name="desc" placeholder="Movie Description">
      <input type="text" name="year" placeholder="Movie Year">
      <input type="file" name="img">
      <input type="submit">
</form>
{% endblock %}

project/project/project/inmakes_product_folder/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href = "{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

project/project/project/inmakes_product_folder/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<img src="{{movie.img.url}}" width="200" height="150">
{{movie.name}}<br>
{{movie.desc}}<br>
{{movie.year}}<br>
<a href="{% url 'movieapp:update' movie.id %}">update</a><br>

{% endblock %}

project/project/project/inmakes_product_folder/movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

project/project/project/inmakes_product_folder/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

{% for i in movie_list %}
<img src="{{i.img.url}}" width="200" height="150">
<a href="{% url 'movieapp:detail' i.id %}">{{i.name}}</a><br>
{% endfor %}
{% endblock %}